# RustScan 2.1.1 Configuration

[range]
start = 1
end = 65535
scan_order = "random"
scan_type = "SYN"

# Performance settings
batch_size = 10000
timeout = 1500
tries = 2
ulimit = 10000
rate = 10000

# Output settings
accessible = false
greppable = false
json = false
no-config = false

# Nmap settings
command = ["-A"]
# script = []

# DNS settings
# dns-servers = []

# Debugging
debug = false